// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThucTap1.Data;

#nullable disable

namespace ThucTap1.Migrations
{
    [DbContext(typeof(ThucTap1Context))]
    [Migration("20240926051652_ThucTap2")]
    partial class ThucTap2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThucTap1.Models.DeTai", b =>
                {
                    b.Property<string>("MaDT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("KinhPhi")
                        .HasColumnType("int");

                    b.Property<string>("NoiThucTap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDT");

                    b.ToTable("DeTai");
                });

            modelBuilder.Entity("ThucTap1.Models.GiangVien", b =>
                {
                    b.Property<int>("MaGV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGV"));

                    b.Property<string>("HoTenGV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhoaMaKhoa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Luong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGV");

                    b.HasIndex("KhoaMaKhoa");

                    b.ToTable("GiangVien");
                });

            modelBuilder.Entity("ThucTap1.Models.HuongDan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeTaiMaDT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("GiangVienMaGV")
                        .HasColumnType("int");

                    b.Property<decimal?>("KetQua")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaGV")
                        .HasColumnType("int");

                    b.Property<int>("MaSV")
                        .HasColumnType("int");

                    b.Property<int?>("SinhVienMaSV")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeTaiMaDT");

                    b.HasIndex("GiangVienMaGV");

                    b.HasIndex("SinhVienMaSV");

                    b.ToTable("HuongDan");
                });

            modelBuilder.Entity("ThucTap1.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("ThucTap1.Models.SinhVien", b =>
                {
                    b.Property<int>("MaSV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSV"));

                    b.Property<string>("HoTenSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhoaMaKhoa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NamSinh")
                        .HasColumnType("int");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSV");

                    b.HasIndex("KhoaMaKhoa");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("ThucTap1.Models.GiangVien", b =>
                {
                    b.HasOne("ThucTap1.Models.Khoa", "Khoa")
                        .WithMany("GiangVien")
                        .HasForeignKey("KhoaMaKhoa");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("ThucTap1.Models.HuongDan", b =>
                {
                    b.HasOne("ThucTap1.Models.DeTai", "DeTai")
                        .WithMany("HuongDan")
                        .HasForeignKey("DeTaiMaDT");

                    b.HasOne("ThucTap1.Models.GiangVien", "GiangVien")
                        .WithMany("HuongDan")
                        .HasForeignKey("GiangVienMaGV");

                    b.HasOne("ThucTap1.Models.SinhVien", "SinhVien")
                        .WithMany("HuongDan")
                        .HasForeignKey("SinhVienMaSV");

                    b.Navigation("DeTai");

                    b.Navigation("GiangVien");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("ThucTap1.Models.SinhVien", b =>
                {
                    b.HasOne("ThucTap1.Models.Khoa", "Khoa")
                        .WithMany("SinhVien")
                        .HasForeignKey("KhoaMaKhoa");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("ThucTap1.Models.DeTai", b =>
                {
                    b.Navigation("HuongDan");
                });

            modelBuilder.Entity("ThucTap1.Models.GiangVien", b =>
                {
                    b.Navigation("HuongDan");
                });

            modelBuilder.Entity("ThucTap1.Models.Khoa", b =>
                {
                    b.Navigation("GiangVien");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("ThucTap1.Models.SinhVien", b =>
                {
                    b.Navigation("HuongDan");
                });
#pragma warning restore 612, 618
        }
    }
}
